import React from 'react'
import { useNavigate } from 'react-router-dom'
import { PageHero } from '@/components/ui/PageHero'
import { PageContainer } from '@/components/ui/PageContainer'
import { GlassCard } from '@/components/ui/GlassCard'
import { SectionTitle } from '@/components/ui/SectionTitle'
import { Button } from '@/components/ui/button'
import { FileText, Shield, AlertTriangle, Scale, Heart } from 'lucide-react'
import { ROUTES } from '@/app/router/routes'

export const TermsPage: React.FC = () => {
  const navigate = useNavigate()

  return (
    <>
      <PageHero
        badgeText="Legal & User Contract"
        title="Terms of Service"
        highlightedTitle="& User Agreement"
        subtitle="Please read these terms carefully. They govern your access to and use of the Kintsugi Mental Wellness & Emotional Companion platform."
        breadcrumbItems={[{ label: 'Terms of Service' }]}
        icon={FileText}
      />

      <PageContainer className="space-y-8 max-w-5xl mx-auto text-left">
        {/* Effective Date Card */}
        <GlassCard accentColor="gold" className="p-6 sm:p-8 space-y-3 border-amber-500/30 bg-amber-500/10 dark:bg-amber-950/20 text-card-foreground">
          <div className="flex items-center gap-3 text-amber-700 dark:text-amber-300 font-semibold text-xs uppercase tracking-wider">
            <Scale className="w-4 h-4 text-amber-500 dark:text-amber-400" />
            <span>Effective Date: July 24, 2026 · Version 2.4</span>
          </div>
          <h2 className="text-xl sm:text-2xl font-bold text-card-foreground font-serif">
            Welcome to Kintsugi
          </h2>
          <p className="text-xs sm:text-sm text-muted-foreground leading-relaxed font-sans">
            By creating an account, downloading, or using the Kintsugi application ("Service"), you agree to be bound by these Terms of Service ("Terms") and our Privacy Policy. If you do not agree to all of these Terms, you may not access or use the Service.
          </p>
        </GlassCard>

        {/* Section 1: Non-Clinical & Emergency Disclaimer */}
        <GlassCard accentColor="purple" className="p-6 sm:p-8 space-y-4 rounded-2xl border-border bg-card text-card-foreground">
          <SectionTitle
            category="Section 1"
            title="Non-Clinical Purpose & Emergency Disclaimer"
            subtitle="Understanding the therapeutic boundaries of Kintsugi"
          />
          <div className="space-y-3 text-xs sm:text-sm text-muted-foreground leading-relaxed">
            <div className="p-4 rounded-xl bg-rose-500/10 border border-rose-500/20 flex items-start gap-3 text-rose-700 dark:text-rose-200">
              <AlertTriangle className="w-5 h-5 text-rose-600 dark:text-rose-400 shrink-0 mt-0.5" />
              <div className="space-y-1">
                <p className="font-bold text-xs uppercase tracking-wider text-rose-700 dark:text-rose-300">
                  CRITICAL SAFETY NOTICE
                </p>
                <p className="text-xs leading-relaxed text-rose-800/90 dark:text-rose-200/90">
                  Kintsugi is <strong>NOT</strong> an emergency crisis service, medical device, or licensed clinical provider. If you are experiencing thoughts of self-harm, suicide, or an acute medical emergency, please call <strong>988</strong> (US Suicide & Crisis Lifeline), <strong>911</strong>, or go to your nearest emergency department immediately.
                </p>
              </div>
            </div>
            <p>
              Kintsugi is designed solely as an empathetic, self-reflective emotional companion and daily wellness tracker. The content generated by our AI conversational engine, mood analytics, and guided breathing prompts is intended for self-improvement and emotional self-awareness only.
            </p>
            <p>
              No physician-patient or therapist-client relationship is established through your use of Kintsugi. Always seek the advice of a qualified mental health professional with any questions regarding clinical conditions.
            </p>
          </div>
        </GlassCard>

        {/* Section 2: Account Registration & Credentials */}
        <GlassCard accentColor="gold" className="p-6 sm:p-8 space-y-4 rounded-2xl border-border bg-card text-card-foreground">
          <SectionTitle
            category="Section 2"
            title="Account Eligibility & Security Obligations"
            subtitle="Your responsibilities as a Kintsugi user"
          />
          <div className="space-y-3 text-xs sm:text-sm text-muted-foreground leading-relaxed">
            <ul className="space-y-2 list-disc list-inside text-muted-foreground">
              <li>
                <strong>Age Requirement:</strong> You must be at least 13 years of age (or 18 years depending on local legal adulthood) to use Kintsugi. Minors between 13 and 18 require parental or legal guardian consent.
              </li>
              <li>
                <strong>Account Accuracy:</strong> You agree to provide accurate and complete registration details and maintain the security of your account credentials.
              </li>
              <li>
                <strong>Credential Protection:</strong> You are solely responsible for maintaining the confidentiality of your login credentials and password. Kintsugi is not liable for unauthorized access resulting from compromised user credentials.
              </li>
              <li>
                <strong>Single User Use:</strong> Accounts are non-transferable and designated for individual personal use only.
              </li>
            </ul>
          </div>
        </GlassCard>

        {/* Section 3: Acceptable Use & Code of Conduct */}
        <GlassCard accentColor="purple" className="p-6 sm:p-8 space-y-4 rounded-2xl border-border bg-card text-card-foreground">
          <SectionTitle
            category="Section 3"
            title="Acceptable Use & Code of Conduct"
            subtitle="Guidelines for respectful and safe platform interactions"
          />
          <div className="space-y-3 text-xs sm:text-sm text-muted-foreground leading-relaxed">
            <p>You agree not to engage in any of the following prohibited actions:</p>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-3 pt-1">
              <div className="p-3.5 rounded-xl bg-muted/30 border border-border space-y-1">
                <h4 className="font-semibold text-xs text-card-foreground">Reverse Engineering & Scraping</h4>
                <p className="text-xs text-muted-foreground">
                  Attempting to decompile, reverse-engineer, extract source code, or scrape AI prompt structures from the platform.
                </p>
              </div>
              <div className="p-3.5 rounded-xl bg-muted/30 border border-border space-y-1">
                <h4 className="font-semibold text-xs text-card-foreground">System Misuse & Exploits</h4>
                <p className="text-xs text-muted-foreground">
                  Injecting malicious code, bypassing rate limiters, or abusing backend API endpoints.
                </p>
              </div>
              <div className="p-3.5 rounded-xl bg-muted/30 border border-border space-y-1">
                <h4 className="font-semibold text-xs text-card-foreground">Prompt Injection & Abuse</h4>
                <p className="text-xs text-muted-foreground">
                  Manipulating AI companion prompts to produce hate speech, harmful instructions, or illegal content.
                </p>
              </div>
              <div className="p-3.5 rounded-xl bg-muted/30 border border-border space-y-1">
                <h4 className="font-semibold text-xs text-card-foreground">Unauthorized Automation</h4>
                <p className="text-xs text-muted-foreground">
                  Using unauthorized bots, scripts, or crawlers to interact with chat endpoints or data stores.
                </p>
              </div>
            </div>
          </div>
        </GlassCard>

        {/* Section 4: Privacy & Client-Side Encryption */}
        <GlassCard accentColor="gold" className="p-6 sm:p-8 space-y-4 rounded-2xl border-border bg-card text-card-foreground">
          <SectionTitle
            category="Section 4"
            title="Intellectual Property & Data Ownership"
            subtitle="Who owns what on the Kintsugi platform"
          />
          <div className="space-y-3 text-xs sm:text-sm text-muted-foreground leading-relaxed">
            <p>
              <strong>Your Content:</strong> You retain complete ownership of all journal entries, mood records, and reflections submitted to Kintsugi. We encrypt your entries client-side using AES-256 Fernet key encryption before sending data to our servers.
            </p>
            <p>
              <strong>Kintsugi Intellectual Property:</strong> All software code, branding assets, logos, design tokens, AI system prompts, and UI components are the exclusive property of Kintsugi. You receive a limited, revocable, non-transferable license to access the platform.
            </p>
          </div>
        </GlassCard>

        {/* Section 5: Limitation of Liability */}
        <GlassCard accentColor="purple" className="p-6 sm:p-8 space-y-4 rounded-2xl border-border bg-card text-card-foreground">
          <SectionTitle
            category="Section 5"
            title="Disclaimer of Warranties & Limitation of Liability"
            subtitle="Legal boundaries of service provision"
          />
          <div className="space-y-3 text-xs sm:text-sm text-muted-foreground leading-relaxed">
            <p className="uppercase text-xs font-mono text-amber-600 dark:text-amber-300">
              SERVICE PROVIDED "AS IS" AND "AS AVAILABLE"
            </p>
            <p>
              KINTSUGI EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.
            </p>
            <p>
              UNDER NO CIRCUMSTANCES SHALL KINTSUGI, ITS DIRECTORS, EMPLOYEES, OR AGENTS BE LIABLE FOR ANY INDIRECT, INCIDENTAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES ARISING FROM YOUR USE OF OR INABILITY TO USE THE SERVICE.
            </p>
          </div>
        </GlassCard>

        {/* Section 6: Termination & Modifications */}
        <GlassCard accentColor="gold" className="p-6 sm:p-8 space-y-4 rounded-2xl border-border bg-card text-card-foreground">
          <SectionTitle
            category="Section 6"
            title="Termination & Service Modifications"
            subtitle="How terms or services may change over time"
          />
          <div className="space-y-3 text-xs sm:text-sm text-muted-foreground leading-relaxed">
            <p>
              We reserve the right to modify, suspend, or discontinue any feature of the platform at any time. We will notify users of material changes to these Terms via in-app banner or email notifications.
            </p>
            <p>
              You may terminate your account at any time via the User Settings panel, which will trigger permanent removal of your account data.
            </p>
          </div>
        </GlassCard>

        {/* Action Button Links */}
        <div className="flex flex-col sm:flex-row items-center justify-between gap-4 pt-4 border-t border-border">
          <Button
            onClick={() => navigate(ROUTES.PUBLIC.PRIVACY_POLICY)}
            variant="outline"
            className="w-full sm:w-auto text-xs gap-2 border-border bg-background text-foreground hover:bg-muted"
          >
            <Shield className="w-4 h-4 text-sky-500" />
            <span>Read Privacy Policy</span>
          </Button>

          <Button
            onClick={() => navigate(ROUTES.PUBLIC.CRISIS_SUPPORT)}
            className="w-full sm:w-auto text-xs gap-2 bg-amber-500 hover:bg-amber-400 text-slate-950 font-bold rounded-xl"
          >
            <Heart className="w-4 h-4 text-slate-950" />
            <span>Access Crisis & Emergency Support</span>
          </Button>
        </div>
      </PageContainer>
    </>
  )
}

export default TermsPage
